project_name: gosimports
changelog:
  skip: true
builds:
  - id: gosimports
    main: ./cmd/gosimports/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
